### ISSUE TITLE
Notification templates customizable and localizable

### ISSUE THREAD

**Issue by humplemann** [JonasJoKuJonas/homeassistant-WebUntis#174]
Hey - I would appreciate it if we could have personal notification templates and also localizations of the strings in it.

Any chance?

**Comment by JonasJoKuJonas** [comment]
The localizations could be implemented in the code but not the translation file.
The template is more difficult because it needs to have multiple if statements to support everything (This is currently done in the python code). But i will look into it

**Comment by sevorl** [comment]
Idea:
Have event triggers for different types of events like "room change", "lesson cancelled"...
Plus have services to get changed rooms, cancelled lessons (maybe this is not even necessary, the action "webuntis.get_timetable" should contain this information already, and could be filtered)

The results of this service could be used to create custom notifications. 
However, this requries some knowledge about processing the json result.


I use a template sensor like this for room changes: 

        {% set lessonList = namespace(lesson=[]) %}
        {% set count = namespace(value=0) %}
          {% set count.value = 0 %}
        {% set lessons = state_attr("sensor.NAME-GOES-HERE_next_lesson_to_wake_up", "day") | from_json %}
        {% for lesson in lessons -%}
        {%- if  lesson.original_rooms.0 is defined -%}
          {% set lessonList.lesson = lessonList.lesson + [lesson.subjects.0.long_name] %}

          {% set count.value = count.value + 1 %}
          {%- endif -%}
        {%- endfor %}
        {%- if count.value == 0 -%}
        Keine Raumwechsel
        {%- else -%}
        {{ lessonList.lesson | unique | join(', ')+" " }}
          {%- endif -%}



or this one for "Vertretungslehrer"

        {% set lessonList = namespace(lesson=[]) %}
        {% set count = namespace(value=0) %}
          {% set count.value = 0 %}
        {% set lessons = state_attr("sensor.NAME-GOES-HERE_next_lesson_to_wake_up", "day") | from_json %}
        {% for lesson in lessons -%}
        {%- if  lesson.original_teachers.0 is defined -%}
          {% set lessonList.lesson = lessonList.lesson + [lesson.subjects.0.long_name] %}
          {% set count.value = count.value + 1 %}
          {%- endif -%}
        {%- endfor %}
        {%- if count.value == 0 -%}
        Keine Vertretungslehrer
        {%- else -%}
        {{ lessonList.lesson | unique | join(', ')+" " }}
          {%- endif -%}

**Comment by JonasJoKuJonas** [comment]
You now can create custom notifications with the new Event Entity in v1.4.0.
Juts add the event entity as trigger to and automation and then phase the data to send your own notification with a template ;)

**Comment by humplemann** [comment]
Thank you! Could you elaborate/show an example of how to phase the data into my notification action? I am not sure how to put in subject, title, etc.

![Image](https://github.com/user-attachments/assets/a30a5720-60af-4e5c-85af-9db08923fc0a)

**Comment by JonasJoKuJonas** [comment]
There will be a test lesson change in the future.
The data should be the same as the json data in the sensors

**Comment by humplemann** [comment]
Yeah sorry, I am not too familiar with what sensor this is, where to find it, how to extract from the JSON and so on. If anyone has come up with an example with the newest version, please feel free to share. Thanks!

**Comment by JonasJoKuJonas** [comment]
Here is an example how it could look
```
to_state:
    entity_id: event.webuntis_lesson_change
    state: '2025-02-12T16:43:45.307+00:00'
    attributes:
      event_type: code
      old_lesson:
        start: '2025-02-12T07:45:00+01:00'
        end: '2025-02-12T09:15:00+01:00'
        subject_id: None
        id: xxx
        lsnumber: xxx
        code: irregular
        type: ls
        subjects: 
          - name: M
             long_name: Mathe
        rooms:
          - name: x
            long_name: xxx
        original_rooms: []
        teachers:
          - name: x
            long_name: xxx
      new_lesson:
        start: '2025-02-12T07:45:00+01:00'
        end: '2025-02-12T09:15:00+01:00'
        subject_id: None
        id: 1317337
        lsnumber: 98996
        code: cancelled
        type: ls
        subjects: []
        rooms:
          - name: x
            long_name: xxx
        original_rooms: []
        teachers:
          - name: x
            long_name: xxx
```
